name = input('Hey user! What is your name?')
print('Hello',name,'!')
print('Nice to meet you.')
color = input('What is your favorite color?')
print('Cool',name,'!')
print('I think',color,'is a beautiful color.')
